### ISSUE TITLE
RingMenu error

### ISSUE THREAD

**Issue by ghost** [obble/modui#60]
This is showing up in the chat after clicking a button in RingMenu http://i.imgur.com/AejNWKX.jpg

**Comment by obble** [comment]
been meaning to check this ~ thanks for creating a ticket. will look into it once nostalrius servers stabilise.

**Comment by obble** [comment]
this seems to have been solved, i'll include the fix in the next revision.

**Comment by ghost** [comment]
Thank you so much! Happy holidays!

**Comment by lystig12** [comment]
I'm still getting this error after upgrading to the newest version of ModUI and RingMenu. Am I doing something wrong, or has it actually been fixed?

**Comment by ghost** [comment]
No, it hasn't been fixed. I'm still getting the error too.

**Comment by ghost** [comment]
@obble Any ETA for the new revision? I really miss using RingMenu :P Thank you!

**Comment by obble** [comment]
hey, no ETA other than "soon" currently. i've been busy with other stuff, but am hoping to fix most things this week once i get around the crazy queues.

**Comment by obble** [comment]
fixed in v78

**Comment by Violet-Vibes** [comment]
This error still appears, even when running latest version of modui and RingMenu
